import React from "react"
import { Card } from "antd"
import Link from "next/link"
import { Button } from "flowbite-react"
const { Meta } = Card

const Detail = () => {
  return (
  <>
  <Card className="m-auto w-3/5">
    <div className="flex">
      <Card className="w-full" cover={<img alt="example" src="/brio.jpeg" />} style={{maxHeight: '450px'}}/>
      {/* <Card className="w-1/2" cover={<img alt="example" src="/brio2.webp" />} /> */}
    </div>
    <h1 className="text-4xl font-bold">Honda Brio</h1>
    <Meta title="" description="Rp 334.800.000 - Rp 493.800.000"/>
    <br></br>
    <p>MAZDA 2 S AT 2011 HIJAU KM PAJAK PANJANG KM RENDAH

KONDISI MOBIL GOOD! SIAP PAKAI LIKE NEW
SPESIFIKASI KENDARAAN :
- DOKUMEN LENGKAP
- WARNA HIJAU
- KM 106RB
- STNK 25/06/2024

HARGA CASH RP 95.850 JT (PAJAK 06/2024)
HARGA PAKET KREDIT RP 85.5 JT

PAKET KREDIT
TDP 13 JT
4TH - RP 2.847 X 47BLN
5TH - RP 2.475 DAN 2.489 X 59BLN
ASURANSI TLO

TDP 25 JT
4TH - RP 2.599 X 47BLN
5TH - RP 2.177 DAN 2.190 X 59BLN
ASURANSI TLO

PAKET KREDIT
TDP 35 JT
3TH - RP 2.675 JT X 35BLN
4TH - RP 2.175 JT X 47BLN
ASURANSI TLO

TDP 45 JT
3TH - RP 2.313 JT X 35BLN
4TH - RP 1.879 JT X 47BLN
ASURANSI TLO

MAZDA 2 S AT 2011 HIJAU KM 106RB

INFO LEBIH LANJUT :
S&K BERLAKU
PERSYARATAN KREDIT :
1. FOTOCOPY KTP SUAMI ISTRI
2. ⁠FOTOCOPY NPWP
3. ⁠FOTOCOPY KK
4. ⁠FOTOCOPY PBB RUMAH
5. ⁠FOTOCOPY SLIP GAJI / SKU
6. ⁠FOTOCOPY REKENING TABUNGAN/KORAN 3 BULAN TERAKHIR

* HARGA MASIH BISA NEGOSIASI HANYA SETELAH CEK UNIT. BISA CEK UNIT SEPUASNYA
* KONFIRMASI TERLEBIH DAHULU SEBELUM DATANG UNTUK PENGECEKAN UNIT SECARA LANGSUNG

ALAMAT :
CABANG 1
SHOWROOM OTO TRAC DI BURSA MOBIL SERBA OTO
BLOK A1 NO.7 S/D 10 PALEM SEMI KARAWACI - TANGERANG

CABANG 2
KAWASAN AUTOMOTIVE EXHIBITION CENTER JL BOULEVARD SELATAN BLOK VA NO. 3 DAN 6, KOTA BKS, JAWA BARAT 17143

UNTUK INFO LEBIH LANJUT HUBUNGI :
RISKA
NO.TELP & WA TERTERA DI PROFIL

THANKYOU</p>
  </Card>
  </>
  )
}
export default Detail
